services:
  backend:
    build: ./backend_flask
    container_name: backend
    env_file: .env.dev
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build: ./frontend_react
    container_name: frontend
    env_file: .env.dev
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
